ProyectLeMoulin/Models/AchatAdminViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace EpicerieModel.Models
{
    /// <summary>
    /// Modèle des données contenu dans Category
    /// </summary>
    public class CategoryViewModel
    {

        public string CategoryId { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "Nom trop long, max. 100 charactéres")]
        [DataType(DataType.Text)]
        [Display(Name = "Nom de la categorie :")]
        public string CategoryName { get; set; }

        [StringLength(100, ErrorMessage = "Nom du contact trop long, max. 200 charactéres")]
        [DataType(DataType.Text)]
        [Display(Name = "Courte description :")]
        public string Description { get; set; }
    }

    /// <summary>
    /// Modèle des données contenu dans Products
    /// </summary>
    public class ProductViewModel
    {

        public string ProductId { get; set; }

        [Required]
        [StringLength(150, ErrorMessage = "Nom trop long, max. 100 charactéres")]
        [DataType(DataType.Text)]
        [Display(Name = "Nom du produit :")]
        public string ProductName { get; set; }

        [StringLength(100, ErrorMessage = "Nom du contact trop long, max. 200 charactéres")]
        [DataType(DataType.Text)]
        [Display(Name = "Courte description :")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Appliquer la TVQ :")]
        public bool TVQ { get; set; }

        [Required]
        [Display(Name = "Appliquer la TPS :")]
        public bool TPS { get; set; }
    }


    /// <summary>
    /// Modèle des données contenu dans Supplier
    /// </summary>
    public class SupplierViewModel
    {

        public string SupplierId { get; set; }

        [Required]
        [StringLength(150, ErrorMessage = "Nom trop long, max. 150 charactéres")]
        [DataType(DataType.Text)]
        [Display(Name = "Nom du fournisseur :")]
        public string SupplierName { get; set; }

        [StringLength(100, ErrorMessage = "Nom du contact trop long, max. 100 charactéres")]
        [DataType(DataType.Text)]
        [Display(Name = "Nom du contact :")]
        public string SupplierContactName { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "Numéro trop long")]  // valeur a confirmer
        [DataType(DataType.Text)]
        [Display(Name = "# Téléphone :")]
        public string SupplierPhone { get; set; }

        [StringLength(20, ErrorMessage = "Numéro trop long")]  // valeur a confirmer
        [DataType(DataType.Text)]
        [Display(Name = "# Fax :")]
        public string SupplierFax { get; set; }

        [StringLength(150, ErrorMessage = "Courriel trop long, max. 150 charactéres")]
        [DataType(DataType.Text)]
        [Display(Name = "Courriel :")]
        public string SupplierMail { get; set; }

        [Required]
        [StringLength(200, ErrorMessage = "Adresse trop longue, max. 200 charactéres")]
        [DataType(DataType.Text)]
        [Display(Name = "Adresse :")]
        public string SupplierAdress { get; set; }

        [StringLength(100, ErrorMessage = "Nom de ville trop long, max. 100 charactéres")]
        [DataType(DataType.Text)]
        [Display(Name = "Ville :")]
        public string SupplierCity { get; set; }

        [StringLength(20, ErrorMessage = "Code trop long")]  // valeur a confirmer
        [DataType(DataType.Text)]
        [Display(Name = "Code Postal :")]
        public string SupplierPostalCode { get; set; }
    }

    /// <summary>
    /// Modèle des données contenu dans Week
    /// </summary>
    public class WeekProductViewModel
    {
        public int WeekId { get; set; }

        [Required]
        public int ProductId { get; set; }

        [Required]
        public int SupplierId { get; set; }

        [Required]
        [Range(1,1000)]
        [DataType(DataType.Currency)]
        [Display(Name = "Cout :")]
        public decimal UnitPrice { get; set; }

        [Required]
        [RegularExpression(@"^\d+$", ErrorMessage = "Nombre entier uniquement")]
        [Display(Name = "Minimum :")]
        public int Quantity { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "Maximum 20 caractères")]
        [DataType(DataType.Text)]
        [Display(Name = "Format :")]
        public string Format { get; set; }
    }

    /// <summary>
    /// Modèle des données contenu dans Taxes
    /// </summary>
    public class TaxesViewModel
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Taxe :")]
        public string Taxe { get; set; }

        [Required]
        [Range(0, 100)]
        [Display(Name = "%")]
        public float Value { get; set; }
    }

    /// <summary>
    /// Modèle des données contenu dans Week
    /// </summary>
    public class WeekViewModel
    {
        [Required]
        public int WeekId { get; set; }

        [Required]
        [Display(Name = "Date de Debut :")]
        public DateTime DateDebut { get; set; }

        [Required]
        [Display(Name = "Date de Fin :")]
        public DateTime DateFin { get; set; }

        [Required]
        [Display(Name = "Date de Distribution :")]
        public DateTime DateRecup { get; set; }
    }

}

ProyectLeMoulin/Models/Taxes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitySample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxes
    {
        public string Taxe { get; set; }
        public double Value { get; set; }
        public int id { get; set; }
    }
}

ProyectLeMoulin/Controllers/AchatAdminController.cs
using EpicerieModel.Models;
using IdentitySample.Models;
using System;
using System.Linq;
using System.Web.Mvc;

namespace IdentitySample.Controllers
{
    [Authorize(Roles = "Administrateur")]
    public class AchatAdminController : Controller
    {
        /// <summary>
        /// Permet d'ouvrir la vue pour Index
        /// Index contient la page qui permet de gêrée la liste d'achats
        /// </summary>
        /// <returns>Une vue avec titre et message</returns>
        public ActionResult Index()
        {
            ViewBag.Title = "Liste des produits";
            ViewBag.message = "Administration de la liste d'achat";
            return View();
        }

        /// <summary>
        /// S'exécute au "Post" de la page Index
        /// Enregistre les Ajouts et Modifications
        /// </summary>
        /// <param name="WeekProduct">Model à utiliser</param>
        /// <returns>Une vue</returns>
        [HttpPost]
        public ActionResult Index(WeekProductViewModel WeekProduct)
        {
            //EpicerieEntities db = new EpicerieEntities();

            //int x = Convert.ToInt16(WeekProduct.ProductId);
            //var Week = (from w in db.Weeks
            //            orderby w.WeekId descending
            //            select w.WeekId).First();

            //if ((from wp in db.WeekProduct
            //     where wp.ProductId == x 
            //     where wp.WeekId == Week 
            //     select wp).Count() == 0)
            //{
            //    WeekProduct wp = new WeekProduct();

            //    wp.WeekId = Week;
            //    wp.ProductId = WeekProduct.ProductId;
            //    wp.SupplierId = WeekProduct.SupplierId;
            //    wp.UnitPrice = WeekProduct.UnitPrice;
            //    wp.Quantity = WeekProduct.Quantity;
            //    wp.Format = WeekProduct.Format;

            //    db.WeekProduct.Add(wp);
            //    db.SaveChanges();
            //}
            //else
            //{
            //    var modifWeekProduct = (from wp in db.WeekProduct
            //                     where wp.ProductId == x
            //                     where wp.WeekId == Week
            //                     select wp).Single();
            
            //    modifWeekProduct.ProductId = WeekProduct.ProductId;
            //    modifWeekProduct.SupplierId = WeekProduct.SupplierId;
            //    modifWeekProduct.UnitPrice = WeekProduct.UnitPrice;
            //    modifWeekProduct.Quantity = WeekProduct.Quantity;
            //    modifWeekProduct.Format = WeekProduct.Format;
            
            //    db.SaveChanges();
            //}

            //getSuppliers();
            //getCategories();

            //ViewBag.Title = "Liste des produits";
            //ViewBag.message = "Administration de la liste d'achat";
            return View();
        }

        /// <summary>
        /// Permet de récupérer les WeekProducts de la semaine courrante
        /// </summary>
        /// <param name="Id">Id du produit voulu</param>
        /// <returns></returns>
        public JsonResult getWeekProducts(int Id)
        {
            //EpicerieEntities db = new EpicerieEntities();

            //int weekbd = (from w in db.Weeks
            //              orderby w.WeekId descending
            //              select w.WeekId).First();

            //var WeekProducts = (from wp in db.WeekProduct
            //                    join p in db.Products
            //                    on wp.ProductId equals p.ProductId
            //                    join cp in db.CategoryProduct
            //                    on p.ProductId equals cp.ProductId
            //                    join c in db.Categories
            //                    on cp.CategoryId equals c.CategoryId
            //                    join s in db.Suppliers
            //                    on wp.SupplierId equals s.SupplierId
            //                    orderby p.ProductName
            //                    where wp.WeekId == weekbd
            //                    where c.CategoryId == Id
            //                    select new
            //                    {
            //                        CategoryId = cp.CategoryId,
            //                        SupplierId = s.SupplierId,
            //                        ProductId = wp.ProductId,
            //                        ProductName = p.ProductName,
            //                        SupplierName = s.SupplierName,
            //                        UnitPrice = wp.UnitPrice,
            //                        Format = wp.Format,
            //                        Quantity = wp.Quantity
            //                    }).ToList();
            var WeekProducts = true;
            return Json(WeekProducts, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Permet d'otenir les informations sur le produit spécifié
        /// pour la semaine courrante.
        /// </summary>
        /// <param name="ProductId">ID du fournisseur</param>
        /// <returns>Json contenant les informations</returns>
        public JsonResult getWeekProductDetails(int ProductId)
        {
            //EpicerieEntities db = new EpicerieEntities();

            //var Week = (from w in db.Weeks
            //            orderby w.WeekId descending
            //            select w.WeekId).First();

            //var weekProduct = ( from wp in db.WeekProduct
            //                    where wp.ProductId == ProductId
            //                    where wp.WeekId == Week
            //                    select new
            //                    {
            //                        week = wp.WeekId,
            //                        Product = wp.ProductId,
            //                        Supplier = wp.SupplierId,
            //                        UnitPrice = wp.UnitPrice,
            //                        Format = wp.Format,
            //                        Qty = wp.Quantity
            //                    }).Single();
            var weekProduct = true;
            return Json(weekProduct, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Permet d'effacer un WeekProduct de la BD
        /// </summary>
        /// <param name="nID">ID du produit</param>
        /// <returns>Retourne à la selection</returns>
        public ActionResult delWeekProduct(int nID)
        {
            //EpicerieEntities db = new EpicerieEntities();

            //var Week = (from w in db.Weeks
            //            orderby w.WeekId descending
            //            select w.WeekId).First();

            //var delWeekProduct = (from wp in db.WeekProduct
            //                      where wp.ProductId == nID
            //                      where wp.WeekId == Week
            //                      select wp).Single();
            //if (delWeekProduct != null)
            //{
            //    db.WeekProduct.Remove(delWeekProduct); 
            //    db.SaveChanges();
            //}
            return Redirect("/AchatAdmin/Index");
        }

        /// <summary>
        /// Permet d'ouvrir la vue pour NewOrder
        /// </summary>
        /// <returns>Une vue avec titre et message</returns>
        public ActionResult NewOrder()
        {
            ViewBag.Title = "Nouvelle Commande";
            ViewBag.message = "Affiche la commande à faire cette semaine";
            return View();
        }

        /// <summary>
        /// Permet d'ouvrir la vue pour Products
        /// </summary>
        /// <returns>Une vue avec titre et message</returns>
        public ActionResult Products()
        {
            ViewBag.Title = "Produits";
            ViewBag.message = "Administration des produits";
            return View();
        }

        /// <summary>
        /// S'exécute au "Post" de la page Products
        /// Enregistre les Ajouts et Modifications
        /// </summary>
        /// <param name="Product">Model à utiliser</param>
        /// <returns>Une vue</returns>
        [HttpPost]
        public ActionResult Products(ProductViewModel product)
        {
            //EpicerieEntities db = new EpicerieEntities();
            //if (product.ProductId == null)
            //{
            //    Products p = new Products();
            //    p.ProductName = product.ProductName;
            //    p.Description = product.Description;
            //    p.TVQ = product.TVQ;
            //    p.TPS = product.TPS;

            //    db.Products.Add(p);
            //    db.SaveChanges();
            //}
            //else
            //{
            //    int x = Convert.ToInt16(product.ProductId);
            //    var modifProduct = (from p in db.Products
            //                        where p.ProductId == x
            //                        select p).Single();
            //    modifProduct.ProductName = product.ProductName;
            //    modifProduct.Description = product.Description;
            //    modifProduct.TVQ = product.TVQ;
            //    modifProduct.TPS = product.TPS;

            //    db.SaveChanges();
            //}

            getProducts();

            ViewBag.Title = "Produits";
            ViewBag.message = "Administration des produits";
            return View();
        }

        /// <summary>
        /// Permet d'obtenir l'ID et le Nom des Products
        /// </summary>
        /// <returns>Json contenant les Products</returns>
        public JsonResult getProducts()
        {
            //EpicerieEntities db = new EpicerieEntities();
            //var products = (from p in db.Products
            //                orderby p.ProductName
            //                select new
            //                {
            //                    id = p.ProductId,
            //                    nom = p.ProductName
            //                }).ToList();

ProyectLeMoulin/Views/AchatAdmin/Categories.cshtml
@model EpicerieModel.Models.CategoryViewModel

@{
    Layout = "~/Views/Shared/_AdminMaster.cshtml";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-4">
        <h3>@ViewBag.Message</h3>
    </div>
</div>

<br />

<p>
    Selectionner une catégorie dans la liste deroulante pour la voir et la modifier, ou cliquer sur le bouton
    nouveau pour en ajouter une.
</p>

<div class="row">
    @Html.Partial("_AdminButonSansMCE")
</div>

<br />

@using (Html.BeginForm("Categories", "AchatAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form",
    @id="Formulaire" }))
{

    @Html.AntiForgeryToken()
    <hr />

    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="row">
        <div class="input-group">
            <table>

                <tr>
                    <td>
                        @Html.LabelFor(c => c.CategoryName, new { @class = "input-group-addon", @style="width:160px" })
                    </td>
                    <td>
                        @Html.TextBoxFor(c => c.CategoryName, new { @class = "form-control", @id="name", @style="width:260px" })
                    </td>
                </tr>

                <tr>
                    <td>
                        @Html.LabelFor(c => c.Description, new { @class = "input-group-addon", @style="width:160px" })
                    </td>
                    <td>
                        @Html.TextAreaFor(c => c.Description, 4, 20,  new {  @class = "form-control", @id="description", @style="width:260px;height:500" })
                    </td>
                </tr>

            </table>
        </div>
    </div>

    <br />

    <div class="row">
        <button type="submit" class="btn btn-success col-md-offset-3 col-md-2" id="save">
            <i class="fa fa-save"></i><b> Enregistrer </b>
        </button>
    </div>

    @Html.HiddenFor(c => c.CategoryId, new { @id = "new123" })
}

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/AdminButonsV2")

    <script>

        $(function () {

            $.ajaxSetup({
                // Disable caching of AJAX responses
                cache: false
            });

            $("#btnSupr").click(function () {
                $("#dialog-confirm").dialog({
                    resizable: false,
                    height: 200,
                    modal: true,
                    buttons: {

                        "Effacer": function () {
                            var x = $("#new123").val();
                            console.log(x);
                            window.open("/AchatAdmin/delCategory?nID=" + x, "_self");
                            $(this).dialog("close");
                        },

                        "Annuler": function () {
                            $(this).dialog("close");
                        }
                    }
                }); // Fin dialog
            }); // Fin btnSupr.click

            Templateitems = Handlebars.compile($("#itemsTemplate").html());

            $.getJSON("getCategories", null, function (data) {

                var result = Templateitems(data);
                $("#ItemsList").html(result);

                $(".items").change(function () {
                    var id = $(this).children(":selected").attr("id");

                    if (id != 0) {
                        $("#btnmodif").show();
                        $("#btnSupr").show();
                        $("#Formulaire").show();
                        $("#new123").val(id);

                        $.getJSON("getCategoryDetails", { CategoryId: id }, function (data) {
                            $("#name").val(data.Nom);
                            $("#description").val(data.description);
                        }); // Fin getSupplierDetails

                    }
                    else $("#btnAnuler").click();

                }); // Fin items .change
            }); // Fin getSuppliers
        }); // Fin des functions
    </script>
}

ProyectLeMoulin/Views/AchatAdmin/Index.cshtml
@model EpicerieModel.Models.WeekProductViewModel

@{
    Layout = "~/Views/Shared/_AdminMaster.cshtml";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-4">
        <h3>@ViewBag.Message</h3>
    </div>
</div>

<br />

<p>Selectionner une catégorie la liste des produits liés ou cliquer sur nouveau pour en ajouter un.</p>

<br />

<div class="row">
    <div class="alert alert-warning" role="alert" id="boutons" style="height:65px;">
        <div class="col-md-3" style="height:auto;">
            <select class="form-control items" id="ItemsList"></select>
        </div>
        <div class="btn btn-success col-md-offset-1" id="btnNew"><i class="fa fa-plus-square"></i> Nouveau</div>
    </div>
</div>

<div class="row" id="List">
    <div id="WeekProductsList" class="col-md-6"></div>
</div>

@using (Html.BeginForm("Index", "AchatAdmin", FormMethod.Post, new
{
    @class = "form-horizontal",
    role = "form",
    @id = "Formulaire"
}))
{

    @Html.AntiForgeryToken()
    <hr />

    @Html.ValidationSummary("", new { @class = "text-danger" })

    <div class="row">
        <div class="input-group">
            <table>
                <tr>
                    <td>
                        <div class="input-group-addon" style="width:160px">Produit :</div>
                    </td>
                    <td>
                        @Html.DropDownListFor(wp => wp.ProductId, new SelectList(new string[] { "Produits" }), new { @class = "form-control prods", @id = "ProductsList" })
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class = "input-group-addon" style = "width:160px">Fournisseur :</div>
                    </td>
                    <td>
                        @Html.DropDownListFor(wp => wp.SupplierId, new SelectList(new string[] { "Fournisseurs" }), new { @class = "form-control supls", @id = "SuppliersList" })
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(wp => wp.UnitPrice, new { @class = "input-group-addon", @style = "width:160px" })
                    </td>
                    <td>
                        @Html.TextBoxFor(wp => wp.UnitPrice, new { @class = "form-control", @id = "UnitPrice" })
                    </td>
                </tr>

                <tr>
                    <td>
                        @Html.LabelFor(wp => wp.Format, new { @class = "input-group-addon", @style = "width:160px" })
                    </td>
                    <td>
                        @Html.TextBoxFor(wp => wp.Format, new { @class = "form-control", @id = "Format" })
                    </td>
                </tr>

                <tr>
                    <td>
                        @Html.LabelFor(wp => wp.Quantity, new { @class = "input-group-addon", @style = "width:160px" })
                    </td>
                    <td>
                        @Html.TextBoxFor(wp => wp.Quantity, new { @class = "form-control", @id = "Quantity" })
                    </td>
                </tr>

            </table>
        </div>
    </div>
    
    <br />

    <div class="row">
        <div class="btn btn-success col-md-2 col-md-offset-1" id="btnAnnuler"><i class="fa fa-undo"></i> Annuler</div>
        <button type="submit" class="btn btn-success col-md-offset-1 col-md-3" id="save">
            <i class="fa fa-save"></i><b> Enregistrer </b>
        </button>
        <div class="btn btn-danger col-md-1 col-md-offset-1" id="btnSupr">Supprimer</div>
    </div>
    
    <div id="dialog-confirm" title="Êtes-vous certain de vouloir effacer?">
        <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Cette action efface de manière permanent et irrecuperable.</p>
    </div>
}

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/x-handlebars-template" id="itemsTemplate">
        <option selected="selected" id=0 value="0">Categories</option>
        {{#each}}
        <option id={{id}} value={{id}}>{{nom}}</option>
        {{/each}}
    </script>

    <script type="text/x-handlebars-template" id="WeekProductsTemplate">
        <div class="row">
            <h4 class="col-xs-4">Produits</h4>
            <h4 class="col-xs-4">Fournisseur</h4>
            <h4 class="col-xs-1">Prix $</h4>
            <h4 class="col-xs-1">Format</h4>
            <h4 class="col-xs-1">Minimum</h4>
            <h4 class="col-xs-1"></h4>
        </div>
        {{#each}}
        <div class="row" id=Product{{ProductId}}>
            <div class="col-xs-4">
                <h5>{{ProductName}}</h5>
            </div>
            <div class="col-xs-4">
                <h5 id="{{ProductId}}">{{SupplierName}}</h5>
            </div>
            <div class="col-xs-1">
                <h5 id="{{ProductId}}">{{UnitPrice}}</h5>
            </div>
            <div class="col-xs-1">
                <h5 id="{{ProductId}}">{{Format}}</h5>
            </div>
            <div class="col-xs-1">
                <h5 id="{{ProductId}}">{{Quantity}}</h5>
            </div>
            <div class="col-xs-1">
                <input id="btnmodif" type="button" value="Modifier" onclick="ModifyWeekProduct('{{ProductId}}', '{{ProductName}}');" class="btn btn-info col-md-offset-1" />
            </div>
        </div>
        {{/each}}
    </script>

    <script type="text/x-handlebars-template" id="SuppliersTemplate">
        {{#each}}
        <option id={{id}} value={{id}}>{{nom}}</option>
        {{/each}}
    </script>

    <script type="text/x-handlebars-template" id="ProductsTemplate">
        {{#each}}
        <option id={{id}} value={{id}}>{{nom}}</option>
        {{/each}}
    </script>

    <script>

        Templateitems = null;
        TemplateWeekProducts = null;
        TemplateSuppliers = null;
        TemplateProducts = null;

        $.ajaxSetup({
            // Disable caching of AJAX responses
            cache: false
        });

        $(function () {
            Templateitems = Handlebars.compile($("#itemsTemplate").html());
            TemplateWeekProducts = Handlebars.compile($("#WeekProductsTemplate").html());

            $("#dialog-confirm").hide();
            $("#Formulaire").hide();

            $.getJSON("/AchatAdmin/getCategories", null, function (data) {

                var result = Templateitems(data);
                $("#ItemsList").html(result);

                $(".items").change(function () {
                    var id = $(this).children(":selected").attr("id");

                    //if ($("#Formulaire").show() == true) {
                    //    $("#Formulaire").hide();
                    //}

                    if (id != 0) {
                        $("#List").show();

                        $.getJSON("/AchatAdmin/getWeekProducts", { Id: id }, function (data) {

                            var result = TemplateWeekProducts(data);
                            $("#WeekProductsList").html(result);

                        }); // Fin de getWeekProducts
                    }
                    else
                    {
                        $("#List").hide();
                    }

                }); // Fin de Categories.items.change
            }); // Fin de getCategories

            $("#btnAnnuler").click(function () {
                $("#boutons").show();
                $("#List").show();
                $("#Formulaire").hide();
                $("#ItemsList option[value='0']").prop('selected', true);
            });

            $("#btnSupr").click(function () {
                $("#dialog-confirm").dialog({
                    resizable: false,
                    height: 200,
                    modal: true,
                    buttons: {

                        "Effacer": function () {
                            var x = $("#new123").val();
                            console.log(x);
                            window.open("/AchatAdmin/delWeekProduct?nID=" + x, "_self");
                            $(this).dialog("close");
                        },

                        "Annuler": function () {
                            $(this).dialog("close");
                        }
                    }
                }); // Fin dialog
            }); // Fin btnSupr.click

            $("#btnNew").click(function () {
                $("#boutons").hide();
                $("#List").hide();
                $("#Formulaire").show();

                TemplateSuppliers = Handlebars.compile($("#SuppliersTemplate").html());
                TemplateProducts = Handlebars.compile($("#ProductsTemplate").html());

                $.getJSON("/AchatAdmin/getSuppliers", null, function (sups) {
                    var result = TemplateSuppliers(sups);
                    $("#SuppliersList").html(result);
                }); // Fin de getSuppliers

                $.getJSON("/AchatAdmin/getProducts", null, function (prod) {
                    var result = TemplateProducts(prod);
                    $("#ProductsList").html(result);

                    $(".prods").change(function () {
                        var id = $(this).children(":selected").attr("id");
                        
                        $("#new123").val(id);
                    })
                }); // Fin de getProducts


            });

        }); // Fin du DOM Load

        function ModifyWeekProduct(id, nom) {

            $("#Formulaire").show();
            $("#List").hide();
            $("#boutons").hide();

            TemplateSuppliers = Handlebars.compile($("#SuppliersTemplate").html());

            $("#ProductsList").html("<option id=" + id + " value=" + id + " selected=true >" + nom + "</option>");
            $.getJSON("/AchatAdmin/getSuppliers", null, function (sups) {
                var result = TemplateSuppliers(sups);
                $("#SuppliersList").html(result);
            }); // Fin de getSuppliers

            $.getJSON("/AchatAdmin/getWeekProductDetails", { ProductId: id }, function (data) {
                $("#UnitPrice").val(data.UnitPrice);
                $("#Format").val(data.Format);
                $("#Quantity").val(data.Qty);
                $("#SuppliersList option[value='" + data.Supplier + "']").prop('selected', true);
                $("#new123").val(data.Product);
            }); // Fin getWeekProductDetails

        } // Fin de ModifyWeekProduct

    </script>
}

ProyectLeMoulin/Views/AchatAdmin/MembersOrders.cshtml
@{    
    Layout = "~/Views/Shared/_AdminMaster.cshtml";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-4">
        <h3>@ViewBag.Message</h3>
    </div>
</div>

ProyectLeMoulin/Views/AchatAdmin/NewOrder.cshtml
@{
    Layout = "~/Views/Shared/_AdminMaster.cshtml";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-4">
        <h3>@ViewBag.Message</h3>
    </div>
</div>

ProyectLeMoulin/Views/AchatAdmin/OldOrders.cshtml
@{
    Layout = "~/Views/Shared/_AdminMaster.cshtml";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-4">
        <h3>@ViewBag.Message</h3>
    </div>
</div>