ProyectLeMoulin/Models/EpicerieViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace IdentitySample.Models
{
    //
    /// <summary>
    /// Modèle de chaque produit
    /// </summary>
    public class listProducts
    {
        public int qty { get; set; }
        public int PID { get; set; }
    }

    public class test1234
    {
        //
        /// <summary>
        /// Modèle de la semaine, contient l'identifiant de la semmaine et la liste des produits
        /// </summary>
        public List<listProducts> obj { get; set; }
        public int week { get; set; }
        public DateTime Debut { get; set; }
        public DateTime Fin { get; set; }
        public DateTime Recup { get; set; }

    }

}

ProyectLeMoulin/Controllers/EpicerieController.cs
using System.Globalization;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Collections.Generic;

namespace IdentitySample.Controllers
{

    [Authorize(Roles = "Membre groupe d'achats")]
    public class EpicerieController : Controller
    {
        /// <summary>
        /// Fait le lien avec la page index
        /// Récupérer les dates de la période d'achat et de récupération
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //EpicerieEntities db = new EpicerieEntities();

            //var week = (from w in db.Weeks
            //            orderby w.WeekId descending
            //            select new test1234
            //            {
            //                Debut = (DateTime)w.Date_Debut,
            //                Fin = (DateTime)w.Date_Fin,
            //                Recup = (DateTime)w.Date_Recuperation
            //            }).Take(1).ToList();

            //ViewBag.Period = week;

            return View();
        }
        
        /// <summary>
        /// Fait le lien avec la page Facture
        /// </summary>
        /// <returns></returns>
        public ActionResult Facture()
        {
            return View();
        }

        /// <summary>
        /// Afficher le message de l'administrateur du groupe D'achats
        /// </summary>
        //public JsonResult Afficher_Message()
        //{

        //}

        /// <summary>
        /// Récupérer les catégories de produits
        /// </summary>
        /// <returns></returns>
        public JsonResult GetWeek()
        {
            //EpicerieEntities db = new EpicerieEntities();

            //var week = (from w in db.Weeks
            //            orderby w.WeekId descending
            //            select new
            //            {
            //                w.WeekId
            //            }).FirstOrDefault();

            var week = true;
            return Json(week, JsonRequestBehavior.AllowGet);
        }



        public JsonResult GetPeriod()
        {
            //EpicerieEntities db = new EpicerieEntities();

            //var week = (from w in db.Weeks
            //            orderby w.WeekId descending
            //            select new
            //            {
            //                Debut = w.Date_Debut,
            //                Fin = w.Date_Fin,
            //                Recup = w.Date_Recuperation
            //            }).FirstOrDefault();
            var week = true;
            return Json(week, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Fait la validation de la semaine pour savoir si le membre
        /// peut passer une commande
        /// </summary>
        /// <returns></returns>
        //public JsonResult ValiderWeek()
        //{
        //    EpicerieEntities db = new EpicerieEntities();

        //    bool valide = false;
        //    var week = (from w in db.Weeks orderby w.WeekId descending select w.WeekId).FirstOrDefault();
        //    var fin = (from w in db.Weeks
        //               where w.WeekId == week
        //               select w.Date_Fin).SingleOrDefault();

        //    if (DateTime.Today <= (DateTime)fin)
        //        valide = true;
        //    return Json(valide, JsonRequestBehavior.AllowGet);
        //}

        /// <summary>
        /// Récupérer La catégorie sélectionnée
        /// </summary>
        /// <returns></returns>
        public JsonResult GetCategories()
        {
            //EpicerieEntities db = new EpicerieEntities();
            //var category = (from c in db.Categories
            //                select new
            //                {
            //                    CategoryID = c.CategoryId,
            //                    CategoryName = c.CategoryName,
            //                    Description = c.Description
            //                }).ToList();
            var category = true;
            return Json(category, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Récupérer les produits selon la catégorie choisie
        /// </summary>
        /// <param name="cat">Id de la catégorie sélectionnée</param>
        /// <returns></returns>
        public JsonResult GetProduits(int cat)
        {
            //EpicerieEntities db = new EpicerieEntities();

            //int weekID = (from w in db.Weeks
            //              orderby w.WeekId descending
            //              select w.WeekId
            //                ).FirstOrDefault();

            //int category = (from c in db.Categories
            //                where c.CategoryId == cat
            //                select c.CategoryId
            //                ).FirstOrDefault();

            //var produit = (from w in db.Weeks
            //               join wp in db.WeekProduct
            //               on w.WeekId equals wp.WeekId
            //               join p in db.Products
            //               on wp.ProductId equals p.ProductId
            //               join cp in db.CategoryProduct
            //               on p.ProductId equals cp.ProductId
            //               where cp.CategoryId == category
            //               && w.WeekId == weekID
            //               select new
            //               {
            //                   WeeK = weekID,
            //                   ProductID = p.ProductId,
            //                   ProductName = p.ProductName,
            //                   Format = wp.Format,
            //                   Price = wp.UnitPrice
            //               }).ToList();

            var produit = true;
            return Json(produit, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Garder ou modifier la bd en async sans affecter la vitesse de l'utilisateur
        /// </summary>
        /// <param name="panier">Liste des produits commandées</param>
        /// <param name="cart">ID de la semaine d'exercice en cours</param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Index(test1234 cart)
        {
            //EpicerieEntities db = new EpicerieEntities();


            //string utilisateur = User.Identity.Name;
            //string guid = db.AspNetUsers.Single(m => m.UserName == utilisateur).Id;

            ////Créer et enregistrer l'Order dans la BD
            //Orders NewOrders = new Orders();

            //NewOrders.UserId = guid;
            //NewOrders.WeekId = cart.week;
            //NewOrders.Commande_Payee = false;

            ////Créer et enregistrer l'OrderDetail dans la BD
            //foreach (var item in cart.obj)
            //{
            //    var price = db.WeekProduct.SingleOrDefault(p => p.ProductId == item.PID && p.WeekId == cart.week).UnitPrice;

            //    OrderDetails NewOdersDetails = new OrderDetails();
            //    NewOdersDetails.ProductId = item.PID;
            //    NewOdersDetails.Quantite = item.qty;
            //    NewOdersDetails.UnitPrice = price;
            //    NewOdersDetails.WeekId = cart.week;
            //    NewOrders.OrderDetails.Add(NewOdersDetails);
            //}


            //db.Orders.Add(NewOrders);

            //await db.SaveChangesAsync();

            //ViewBag.Steeve = "ton panier";
            //}
            //else
            //{
            //    ViewBag.Steeve = "erreur";
            //}
            //}

            return Redirect("/Epicerie/Facture");

        }
        //----------------------------------------------------------------------------------------------------------------------

        /// <summary>
        /// Récupères les informations du membre pour afficher
        /// </summary>
        /// <param name="OID">OrderID sélectionné</param>
        /// <returns></returns>
        public JsonResult GetMembre(int OID)
        {
            //EpicerieEntities db = new EpicerieEntities();

            //string utilisateur = User.Identity.Name;
            //string guid = db.AspNetUsers.Single(m => m.UserName == utilisateur).Id;

            //var order = (from o in db.Orders
            //             join a in db.AspNetUsers
            //             on o.UserId equals a.Id
            //             join w in db.Weeks
            //             on o.WeekId equals w.WeekId
            //             where o.UserId == guid
            //             && o.OrderId == OID
            //             orderby o.OrderId descending
            //             select new
            //             {
            //                 Membre = a.Prenom + " " + a.Nom,
            //                 OrderID = o.OrderId,
            //                 Fin = w.Date_Fin
            //             }).ToList();

            //var week = (from w in db.Weeks
            //            join o in db.Orders
            //            on w.WeekId equals o.WeekId
            //            where o.WeekId == OID
            //            orderby w.WeekId descending
            //            select new test1234
            //            {
            //                Fin = (DateTime)w.Date_Fin,
            //                Recup = (DateTime)w.Date_Recuperation
            //            }).ToList();

            //ViewBag.GetMembre = week;
            var order = true;

            return Json(order, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Récupérer le OrderId de la facture à afficher
        /// </summary>
        /// <returns></returns>
        public JsonResult GetOrder()
        {
            //EpicerieEntities db = new EpicerieEntities();

ProyectLeMoulin/Views/Epicerie/Facture.cshtml
@model IdentitySample.Models.test1234
@using System.Globalization

@section Scripts
{

    @*Template des Catégories*@
    <script type="text/x-handlebars-template" id="OrdersTemplate">
        <select id="OrderOutput" name="Orders" class="form-control orders">
            <option selected="selected" id=0 value="0">Choisissez une facture</option>
            {{#each}}
            <option id={{OrderID}} value="{{OrderID}}">{{OrderID}}</option>
            {{/each}}
        </select>
    </script>
    @*Template des Détails*@
    <script type="text/x-handlebars-template" id="DetailsTemplate">
        <div class="row">
            <h4 class="col-xs-4">Produit</h4>
            <h4 class="col-xs-3">Format</h4>
            <h4 class="col-xs-2">Quantite</h4>
            <h4 class="col-xs-1">Prix</h4>
            <h4 class="col-xs-1">SousTotal</h4>
        </div>
        {{#each}}
        <div class="row" id=Detail{{ProductID}}>
            <div class="col-xs-4">
                <h5 id="Name{{ProductID}}">{{Produit}}</h5>
            </div>
            <div class="col-xs-3">
                <h5 id="Format{{ProductID}}">{{Format}}</h5>
            </div>

            <div class="col-xs-2">
                <h5 id="Quantité{{ProductID}}">{{Quantite}}</h5>
            </div>
            <div class="col-xs-1">
                <h5 id="Format{{ProductID}}">{{Prix}}</h5>
            </div>
            <div class="col-xs-1">
                <input class="sTotal col-sx-1" id="STotal{{ProductID}}" type="text" value="{{SousTotal}}" name="{{SousTotal}}.qty" readonly="readonly" />
            </div>

        </div>
        {{/each}}
    </script>

<script type="text/x-handlebars-template" id="MembresTemplate">
    <div class="row">
        <h4 class="col-xs-4">No. Facture</h4>
        <h4 class="col-xs-3">Membre</h4>
        <h4 class="col-xs-3">Date</h4>
    </div>
    <div class="row" id="Detail">
        <div class="col-xs-4">
            <h5 id="Name">{{OrderID}}</h5>
        </div>
        <div class="col-xs-3">
            <h5 id="Membre">{{Membre}}</h5>
        </div>
        <div class="col-xs-3">
            <h5 id="Date">{{Fin}}</h5>
        </div>
    </div>
</script>

    <script type="text/javascript">
        templateOrders = null;
        templateDetails = null;
        templateMembres = null;
       

        $(function () {
            templateOrders = Handlebars.compile($("#OrdersTemplate").html());
            templateDetails = Handlebars.compile($("#DetailsTemplate").html());
            
            $.getJSON("/Epicerie/GetOrder", null, function (data) {
                var result = templateOrders(data);
                $("#OrdersOutput").html(result);

                $(".orders").change(function () {
                    var id = $(this).children(":selected").attr("id");
                    
                    if (id != 0) {

                        AfficherMembre(id);

                        $.getJSON("/Epicerie/GetDetails", { OID: id }, function (data) {
                            var result = templateDetails(data);
                            $("#DetailsOutput").html(result);

                        });//GetDetails
                    }
                });
            });//GetOrders
        });

        function AfficherMembre(id) {
            templateMembres = Handlebars.compile($("#MembresTemplate").html());

            $.getJSON("/Epicerie/GetMembre", { OID: id }, function (data) {
                var result = templateMembres(data);
                console.log(data);
                var Somme = 0;
                $("#MembresOutput").html(result);
                $(".sTotal").each(function(){
                    Somme += (this).val();
                });
                //console.log(Somme)
                $("#SommeOutput").html(Somme);
            });
        };
    </script>
}

<div id="dvContainer" class="row">
    <div id="OrdersOutput" class="col-md-12"></div>
    <div id="MembresOutput" class="col-md-12"></div>
    <div id="DetailsOutput" class="col-md-12"></div>
    <div id="SommeOutput" class="col-md-12"></div>
</div>
    
<div>@Html.ActionLink("Retour", "Index")</div>

ProyectLeMoulin/Views/Epicerie/Index.cshtml
@model IdentitySample.Models.test1234
@using System.Globalization



@section Scripts
{

    @*Template des Catégories*@
    <script type="text/x-handlebars-template" id="CategoriesTemplate">
        <select id="CategoryOutput" name="Categories" class="form-control">
            <option selected="selected" id=0 value="0">Choisissez une categorie</option>
            {{#each}}
            <option id={{CategoryID}}>{{CategoryName}}</option>
            {{/each}}
        </select>
    </script>

    @*Template des produits*@
    <script type="text/x-handlebars-template" id="ProductsTemplate">
        <div class="row">
            <h4 class="col-xs-4">Produits</h4>
            <h4 class="col-xs-3">Format</h4>
            <h4 class="col-xs-2">Prix $</h4>
            <h4 class="col-xs-2">Qty</h4>
            <h4 class="col-xs-1">Ajouter au panier</h4>
        </div>
        {{#each}}
        <div class="row" id=Product{{ProductID}}>
            <div class="col-xs-4">
                <h5 id="Name{{ProductID}}">{{ProductName}}</h5>
            </div>
            <div class="col-xs-3">
                <h5 id="Format{{ProductID}}">{{Format}}</h5>
            </div>
            <div class="col-xs-2">
                <h5 id="Price{{ProductID}}">{{Price}}</h5>
            </div>
            <div class="col-xs-2">
                <input class=" col-xs-12" id="Quantity{{ProductID}}" type="text" value="0" />
            </div>
            <div class="col-xs-1">
                <input id="AddProduct{{ProductID}}" type="submit" value="Ajouter" class="btn btn-success" onclick="AjouterPanier('{{ProductID}}')" />
            </div>
        </div>
        {{/each}}
    </script>
    @*Template du panier*@
    <script type="text/x-handlebars-template" id="CartTemplate">

        <div id="prod{{id}}" class="row produit">
            <input type="hidden" name="{{name}}.PID" value="{{id}}" />
            <div id="pname{{id}}" class="col-xs-3">{{nom}}</div>
            <div id="pformat{{id}}" class="col-xs-2">{{format}} </div>
            <div id="pprix{{id}}" class="col-xs-1">{{prix}}</div>
            <input class=" col-xs-1" id="CartQuantity{{id}}" type="text" value="{{qty}}" name="{{name}}.qty" readonly="readonly" />
            <div id="psous{{id}}" class="col-xs-2">{{Soustotal}}</div>
            <div class="col-xs-1"><input id="Cartupdate{{id}}" type="button" value="Modifier" onclick="ModifierProduit('{{id}}')" class="btn btn-warning" /></div>
            <div class="col-xs-1"><input id="Cartdelete{{id}}" type="button" value="Enlever" onclick="SupprimerProduit('{{id}}')" class="btn btn-danger" /></div>
        </div>
    </script>
    <script type="text/javascript">
        templateCategories = null;
        templateProducts = null;
        templateCart = null;
        var prix = 0;
        var action = "";
        var total = 0;
        var ancienprix = 0;
        var fTotal = 0;
        //variable tres important determine l'indice dans la liste objets
        var i = 0;

        $(function () {
            templateCategories = Handlebars.compile($("#CategoriesTemplate").html());
            templateProducts = Handlebars.compile($("#ProductsTemplate").html());
            templateCart = Handlebars.compile($("#CartTemplate").html());

            $.getJSON("/Epicerie/GetWeek", null, function (data) {
                var result = templateCategories(data);
                $("#CategoriesOutput").html(result);

                $.getJSON("/Epicerie/GetCategories", null, function (data) {
                    var result = templateCategories(data);
                    $("#CategoriesOutput").html(result);

                    //Afficher les catégories
                    $("#CategoryOutput").change(function () {
                        var id = $(this).children(":selected").attr("id");
                        if (id != 0) {
                            $.getJSON("/Epicerie/GetProduits", { cat: id }, function (data) {
                                var result = templateProducts(data);
                                $("#week123").val(data[0].WeeK);
                                $("#ProductsOutput").html(result);
                            });//GetProducts
                        }
                    })//GetCategories
                });
            })
        });
        function AjouterPanier(id) {
            action = "AJOUT";
            if ($("#Quantity" + id).val() > 0) {
                console.log(id);
                var p = $("#Price" + id).html();
                var q = $("#Quantity" + id).val();
                var sous = p * q;
                var produit = {
                    id: id,
                    nom: $("#Name" + id).html(),
                    format: $("#Format" + id).html(),
                    prix: p,
                    qty: q,
                    Soustotal: sous.toFixed(2),
                    //le name va a creer la relation avec le objet dans le model comme obj[0], obj[1], etc...
                    name: "obj[" + i + "]"
                };

                i += 1;
                var result = templateCart(produit);
                console.log(result);
                $("#CartOutput").append(result);
                Caltotal(id, p, q);

                $("#AddProduct" + id).attr("disabled", "disabled");
                $("#AddProduct" + id).attr("class", "btn btn-default");
                $("#AddProduct" + id).val("Ajouté");
                $("#Quantity" + id).attr("disabled", "disabled");
                $("#Panier").attr("hidden", false);
            }
            else {
                alert("SVP veuillez indiquer une quantité");
            }
        };

        function SupprimerProduit(id) {
            action = "ENLEVER";
            Caltotal(id);
            $("#prod" + id).remove();
            $("#AddProduct" + id).attr("disabled", false);
            $("#AddProduct" + id).attr("class", "btn btn-success");
            $("#AddProduct" + id).val("OK");
            $("#Quantity" + id).attr("disabled", false);
            $("#Quantity" + id).val(0);
            if (total < 1) {
                $("#Panier").attr("hidden", true);
            }
        }

        function ModifierProduit(id) {
            if ($("#Cartupdate" + id).val() == "Modifier") {
                $("#Cartupdate" + id).val("OK");
                $("#Cartupdate" + id).attr("class", "btn btn-success");
                $("#CartQuantity" + id).attr("readonly", false);

            } else {
                if ($("#Cartupdate" + id).val() == "OK") {
                    $("#Cartupdate" + id).val("Modifier");
                    $("#Cartupdate" + id).attr("class", "btn btn-warning");
                    $("#CartQuantity" + id).attr("readonly", true);
                    action = "MODIF";
                    Caltotal(id);
                }
            }
        }

        function Caltotal(id, p, q) {
            if (action == "AJOUT") {
                prix = p * q;
                total += prix;
                $("#totalOutput").html(total.toFixed(2));
            }
            if (action == "ENLEVER") {
                var montant = 0;
                montant = $('#psous' + id).html();
                total -= parseFloat(montant);
                $("#totalOutput").html(total.toFixed(2));
            }
            if (action == "MODIF") {
                var ancien = 0;
                var nprix = 0;
                var qt = 0;

                ancien = $('#psous' + id).html();
                ancienprix = parseFloat(ancien);
                qt = $('#CartQuantity' + id).val();
                nprix = $("#pprix" + id).html();
                nprix = parseFloat(nprix);
                prix = qt * nprix;
                $('#psous' + id).html(prix.toFixed(2));
                total += prix;
                total -= ancienprix;
                $("#totalOutput").html(total.toFixed(2));
            }

        };


    </script>
}

<div class="row">
    <div id="Message"></div>
</div>

<div class="container" id="BillButtons">
    <div>@Html.ActionLink("Factures", "Facture")</div>
</div>

<div id="Cat" class="Container">
    <div class="col-md-12">
        @foreach (var p in ViewBag.Period)
        {
            <h4>
                Période de commande du @p.Debut.ToString("dd MMMM yyyy", CultureInfo.CreateSpecificCulture("fr-CA"))
                au                     @p.Fin.ToString("dd MMMM yyyy", CultureInfo.CreateSpecificCulture("fr-CA"))
            </h4>
            <h4>
                Récupération le        @p.Recup.ToString("dd MMMM yyyy", CultureInfo.CreateSpecificCulture("fr-CA"))
            </h4>
        }
    </div>

    <div class="col-md-4">

        <div id="CategoriesOutput" class="col-md-12"></div>
    </div>
    <div id="ProductsOutput" class="col-md-6"></div>

    <div>@ViewBag.Steeve</div>
    <hr />

    <div class="container" id="Panier" hidden="hidden">
        <div class="row">
            @using (Html.BeginForm("Index", "Epicerie", FormMethod.Post, new { @class = "form-horizontal", role = "form", @id = "Formulaire" }))
            {
        <!-- objet cachet qui garde le valeur de la semaine courrante metre le valeur avec le id-->
                @Html.HiddenFor(m => m.week, new { @Value = "test", @id = "week123" })
                <div id="CartOutput" class="col-md-12">
                    <div class="row">
                        <h4 class="col-xs-3">Produits</h4>
                        <h4 class="col-xs-2">Format</h4>
                        <h4 class="col-xs-1">Prix $</h4>
                        <h4 class="col-xs-1">Qty</h4>
                        <h4 class="col-xs-2">Sous-Total</h4>
                        <h4 class="col-xs-1">Modifier</h4>
                        <h4 class="col-xs-1">Enlever</h4>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-xs-7"></div>
                    <div class="col-xs-2">
                        <h3><b>total $</b></h3>
                        <div class="col-xs-3" id="totalOutput">
                            <h3><b>0</b></h3>
                        </div>
                    </div><div class="col-xs-9"></div>
                    <div style="height:40px; float:left;"></div>
                    <div class="row col-md-12">
                        <!--Boutton pour envoyer le panier au serveur-->
                        <div style="text-align:center"><h3><b>En cliquant sur le bouton "Envoyez" vous ne pourrez pus effectuer de changement</b></h3></div>
                        <div class="col-xs-5"></div><input id="NewBill" type="submit" class="col-xs-2 btn btn-primary" value="Envoyer" />
                    </div>
                </div>
            }
        </div>
    </div>
</div>